name: emerald_app
description: EmeraldApp - A private Android app for financial tracking life.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # State Management
  provider: ^6.1.1

  # Charts
  fl_chart:

  # I/O & Permissions
  path_provider: ^2.1.1
  permission_handler:
  file_picker:
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true

